kong:
  image: kong
  ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 7946:7946
    - 7946:7946/udp
  environment:
    KONG_DATABASE: postgres
    KONG_PG_HOST: ${KONG_PG_HOST}
  # logging:
  #   driver: awslogs
  #   options:
  #     awslogs-group: ${CLOUDWATCH_LOG_GROUP}
  stdin_open: true