.catalog:
  name: SumoLogic Collector
  version: 1.0-rancher0
  uuid: logs-0
  description: |
    Export Logs
  questions:
    - variable: "collector_token"
      type: "string"
      required: true
      label: "Collector Token"
      description: Token from SumoLogic for the collector you're using (part of the URL after receiver/v1/http/)'
services:
  logspout-sumo:
    scale: 1
    start_on_create: true
      