version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${ADMIN_PWD}
      GF_SECURITY_ADMIN_USER: ${ADMIN_USERNAME}
      GF_SECURITY_SECRET_KEY: ${SECRET_KEY}
    ports:
    - 3000:3000/tcp
