.catalog:
  name: Grafana Monitoring UI
  version: 1.0-rancher0
  uuid: grafana-0
  description: |
    Analytics and monitoring UI based on telegraf and influx data
  questions:
    - variable: "admin_username"
      type: "string"
      required: true
      label: "Admin Password"
    - variable: "admin_pwd"
      type: "string"
      required: true
      label: "Admin Password"
    - variable: "secret_key"
      type: "string"
      required: true
      label: "Secret Key"
services:
  grafana:
    scale: 1
    start_on_create: true
