version: '2'
services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_SECRET_KEY: su2Tong2zoocie
    ports:
    - 3000:3000/tcp
