influxdb:
  ports:
    - 8086:8086
    - 8083:8083
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.project_service.name=influxdb/influxdb
  image: influxdb:1.0.1
telegraf:
  ports:
  - 8092:8092/udp
  environment:
    HOST_ETC: /rootfs/etc
    HOST_MOUNT_PREFIX: /rootfs
    HOST_PROC: /rootfs/proc
    HOST_SYS: /rootfs/sys
    LOGSPOUT: ignore
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: telegraf-conf
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.container.dns: 'true'
  command:
  - -config
  - /config/telegraf/telegraf.conf
  image: telegraf:1.0.1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - /:/rootfs:ro
  volumes_from:
  - telegraf-conf
  net: host
telegraf-conf:
  environment:
    LOGSPOUT: ignore
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  command:
  - config/telegraf
  image: objectpartners/rancher-container-conf:latest
  volumes:
  - /config/telegraf
grafana:
  image: grafana/grafana:latest
  environment:
    GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PWD}
    GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME}
    GF_SECURITY_SECRET_KEY: ${GRAFANA_SECRET_KEY}
  ports:
  - 3000:3000/tcp
logspout_firehose:
  image: 302265824077.dkr.ecr.us-west-2.amazonaws.com/logspout-firehose:d2e85f2
  command: 'syslog://logstash:5000'
  links:
    - logstash
  environment:
    AWS_ACCESS_KEY: ${LOGSPOUT_AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${LOGSPOUT_AWS_SECRET_KEY}
    AWS_REGION: ${AWS_REGION}
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock